services:
  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.22.10
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    privileged: false
    environment:
      DOTNET_EnableDiagnostics: "0"
      PseudonymizationService: "Vfps"
      Vfps__Address: "dns:///vfps:8081"
      AnonymizationEngineConfigPath: "/opt/fhir-pseudonymizer/anonymization.yaml"
      UseSystemTextJsonFhirSerializer: "true"
    volumes:
      - "./anonymization.yaml:/opt/fhir-pseudonymizer/anonymization.yaml:ro"
    ports:
      - "127.0.0.1:8083:8080"